myresume/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static  import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('resumeapp.urls')),
]


urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

resumeapp/urls.py
from django.contrib import admin
from django.urls import path
from resumeapp.views import  *
app_name="myresume"
urlpatterns = [ path('',home_view,name='index'),
                path('skill',skill_view,name='skill'),
                path('language',lang_view,name='lang'),
                path('bio',bio_view,name='bio'),
                path('study',study_view,name='study')]

resumeapp/models.py
from django.db import models

# Create your models here.

resumeapp/views.py
from django.shortcuts import render

# Create your views here.
def  home_view(request):
    return render(request,'myresume/index.html')
def skill_view(request):
    return  render(request,'myresume/skill.html')

def  lang_view(request):
    return render(request,'myresume/language.html')
def bio_view(request):
    context={'my_email':'kmhoseini76@gmail.com','my_phone':'0912-2580590','my_name':"بهار",'my_last_name':'محمدحسینی','my_age':'47'}
    return  render(request,'myresume/bio.html',context)

def study_view(request):
    return render(request,'myresume/study.html')
'''
def  project_view(request):
    return  render(request,'project.html')



'''

templates/myresume/base.html
{% load static  %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static 'img/favicon.png' %}"  type="image/png">
        <title>بهار</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{%static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{%static 'vendors/linericon/style.css' %}">
        <link rel="stylesheet" href="{%static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{%static 'vendors/owl-carousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{%static 'vendors/lightbox/simpleLightbox.css' %}">
        <link rel="stylesheet" href="{%static 'vendors/nice-select/css/nice-select.css' %}">
        <link rel="stylesheet" href="{%static 'vendors/animate-css/animate.css' %}">
        <link rel="stylesheet" href="{%static 'vendors/flaticon/flaticon.css' %}">
        <!-- main css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    </head>
    <body>
        
        <!--================Header Menu Area =================-->
        <header class="header_area">
            <div class="main_menu" id="mainNav">
            	<nav class="navbar navbar-expand-lg navbar-light">
					<div class="container box_1620">
						<!-- Brand and toggle get grouped for better mobile display -->
						<a class="navbar-brand logo_h" href="{%url 'myresume:index' %}"><img src="{% static 'img/logo.jpg' %} "></a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
							<ul class="nav navbar-nav menu_nav ml-auto">
								<li class="nav-item active"><a class="nav-link" href="{%url 'myresume:index' %}">خانه</a></li> 
								
								<li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">توانایی ها</a>
									<ul class="dropdown-menu">
										<li class="nav-item"><a class="nav-link" href="{%url 'myresume:skill' %}">مهارتها</a></li>
										<li class="nav-item"><a class="nav-link" href="{%url 'myresume:study' %}">تحصیلات</a></li>
										<li class="nav-item"><a class="nav-link" href="{%url 'myresume:lang' %}">زبانها</a></li>
									</ul>
								</li> 
								<li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blog</a>
									<ul class="dropdown-menu">
										<li class="nav-item"><a class="nav-link" href="{%url 'myresume:index' %}">Blog</a></li>
										<li class="nav-item"><a class="nav-link" href="{%url 'myresume:index' %}">Blog Details</a></li>
									</ul>
								</li> 
								<li class="nav-item"><a class="nav-link" href="{%url 'myresume:bio' %}">درباره من</a></li>
							</ul>
						</div> 
					</div>
            	</nav>
            </div>
        </header>
        <!--================Header Menu Area =================-->
      {% block content %}

      {% endblock %}
       
        <!--================Footer Area =================-->
        <footer class="footer_area p_120">
        	<div class="container">
        		<div class="row footer_inner">
        			<div class="col-lg-5 col-sm-6">
        				<aside class="f_widget ab_widget">
        					<div class="f_title">
        						<h3>About Me</h3>
        					</div>
        					<p>Do you want to be even more successful? Learn to love learning and growth. The more effort you put into improving your skills,</p>
        					<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
        				</aside>
        			</div>
        			<div class="col-lg-5 col-sm-6">
        				<aside class="f_widget news_widget">
        					<div class="f_title">
        						<h3>Newsletter</h3>
        					</div>
        					<p>Stay updated with our latest trends</p>
        					<div id="mc_embed_signup">
                                <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
                                	<div class="input-group d-flex flex-row">
                                        <input name="EMAIL" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
                                        <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>		
                                    </div>				
                                    <div class="mt-10 info"></div>
                                </form>
                            </div>
        				</aside>
        			</div>
        			<div class="col-lg-2">
        				<aside class="f_widget social_widget">
        					<div class="f_title">
        						<h3>Follow Me</h3>
        					</div>
        					<p>Let us be social</p>
        					<ul class="list">
        						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
        						<li><a href="#"><i class="fa fa-twitter"></i></a></li>
        						<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
        						<li><a href="#"><i class="fa fa-behance"></i></a></li>
        					</ul>
        				</aside>
        			</div>
        		</div>
        	</div>
        </footer>
        <!--================End Footer Area =================-->
        
        
        
        
        
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/stellar.js' %}"></script>
        <script src="{% static 'vendors/lightbox/simpleLightbox.min.js'%}"></script>
        <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/isotope-min.js' %}"></script>
        <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'vendors/counter-up/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'vendors/counter-up/jquery.counterup.min.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <!--gmaps Js-->
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
        <script src="{% static 'js/gmaps.min.js' %}"></script>
        <script src="{% static 'js/theme.js' %}"></script>
    </body>
</html>

templates/myresume/bio.html
{%extends 'myresume/base.html'%}
{%load static %}
{% block content %}

<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.2" data-stellar-vertical-offset="0" data-background="">
        </div>
        <section id="about" class="about">
            <div class="container" data-aos="fade-up">

                <div class="container">
                    <div class="section-title">
                        <br>
                        <br>
                        <br>
                        <h2>درباره من </h2>

                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <img src="{% static 'img/about.jpg' %}" class="img-fluid" alt="">
                        </div>
                        <div class="col-lg-8 pt-4 pt-rg-0 content">
                            <h3>مشخصات</h3>
                            <p class="fst-italic">
                            </p>
                            <div class="row">
                                <div class="col-lg-6">
                                    <ul>
                                        <li><i class="bi bi-rounded-right"></i> <strong>نام خانوادگی: </strong> {{my_last_name}}</li>
                                        <li><i class="bi bi-rounded-right"></i> <strong>تاریخ تولد: </strong> 1355 شهریور </li>
                                        <li><i class="bi bi-rounded-right"></i> <strong>وبسایت: </strong> www.example.com </li>
                                        <li><i class="bi bi-rounded-right"></i> <strong>تلفن: </strong> +98 <span></span> {{my_phone}}</li>
                                        <li><i class="bi bi-rounded-right"></i> <strong>شهر : </strong> تهران</li>
                                    </ul>
                                </div>
                                <div class="col-lg-6">
                                    <ul>
                                        <li><i class="bi bi-rounded-right"></i> <strong>نام: </strong> {{my_name}}</li>
                                        <li><i class="bi bi-rounded-right"></i> <strong>سن: </strong> {{my_age}}</li>
                                        <li><i class="bi bi-rounded-right"></i> <strong>تحصیلات: </strong> کارشناس ارشد </li>
                                        <li><i class="bi bi-rounded-right"></i> <strong>ایمیل: </strong>{{my_email}} </li>
                                        <li><i class="bi bi-rounded-right"></i> <strong>فریلنسر: </strong>دورکار</li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                  </div>
                </div>
            </div>
        </section><!-- End About Section -->
    </div>
</section>
<!--================End Home Banner Area =================-->
<main id="main">

    <!-- ======= About Section ======= -->



    {%endblock %}

templates/myresume/index.html
 {%extends  'myresume/base.html'%}
 {%load static %}
{% block content %}
        <!--================Home Banner Area =================-->
        <section class="home_banner_area">
            <div class="banner_inner">
				<div class="container">
					<div class="row">
						<div class="col-lg-6">
							<div class="home_left_img">
								<img src="{% static 'img/banner/home-left-1.jpg' %}">
							</div>
						</div>
						<div class="col-lg-6">
							<div class="banner_content">
							
								<h2>بهار محمدحسینی</h2>
								<p>از آموختن و  باز هم آموختن  نترسیم، رشد ما با آموختن اتفاق  می افتد</p>
								<a class="banner_btn" href="#">پس همین حالا شروع کن</a>
							</div>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        
		{%endblock %}     

templates/myresume/language.html
{%extends  'myresume/base.html'%}
{%load static %}
{% block content %}
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-left">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.5" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<br>
						<br>
						<h2>آشنایی با زبان </h2>
						<p> فارسی</p>
						<p> ترکی آذری و استانبولی</p>
						<p> انگلیسی</p>
						<p> روسی </p>
						<br>
						<br>
						<br>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
                
      
     
		{%endblock %}  

templates/myresume/skill.html
{%extends 'myresume/base.html'%}
{%load static %}
{% block content %}

<!--================Home Banner Area =================-->
<section class="banner_area">
	<div class="banner_inner d-flex align-items-center">
		<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background="">
		</div>
		<div class="container">
			<div class="banner_content text-center">
				<h2>مهارتها </h2>
				<div class="page_link">
					<p>معلم هنرستان در رشته تصویر سازی</p>
					<br>
					<p> آشنا با نرم افزارهای تدوین فیلم </p>
					<br>
					<p> آشنا با نرم افزارهای مدلسازی سه بعدی </p>
					<br>
					<p> مدیریت کلاس </p>
				</div>

			</div>
		</div>
	</div>
</section>
<!--================End Home Banner Area =================-->

<!--================Welcome Area =================-->
<section class="welcome_area p_100">
	<div class="container">
		<div class="row welcome_inner">
			
			<div class="col-lg-6">
				<div class="tools_expert">
					<h3>مهارت در زمینه </h3>
					<div class="skill_main">
						<div class="skill_item">
							<h4>After Effects <span class="counter">85</span>%</h4>
							<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0"
									aria-valuemax="100"></div>
							</div>
						</div>
						<div class="skill_item">
							<h4>Photoshop <span class="counter">90</span>%</h4>
							<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
									aria-valuemax="100"></div>
							</div>
						</div>
						<div class="skill_item">
							<h4>Illustrator <span class="counter">100</span>%</h4>
							<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0"
									aria-valuemax="100"></div>
							</div>
						</div>
						<div class="skill_item">
							<h4>Premier <span class="counter">95</span>%</h4>
							<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="95" aria-valuemin="0"
									aria-valuemax="100"></div>
							</div>
						</div>
						<div class="skill_item">
							<h4>AutoDesk maya <span class="counter">65</span>%</h4>
							<div class="progress">
								<div class="progress-bar" role="progressbar" aria-valuenow="65" aria-valuemin="0"
									aria-valuemax="100"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!--================End Welcome Area =================-->

{%endblock %}

templates/myresume/study.html
{%extends  'myresume/base.html'%}
{%load static %}
{% block content %}
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-left">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.5" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>تحصیلات</h2>
						<br>
						<br>
						<p> کارشناسی مهندسی کامپیوتر نرم افزار از دانشگاه فردوسی مشهد</p>
						<p> کارشناسی ارشد مهندسی کامپیوتر نرم افزار از دانشگاه آزاد  واحد تهران جنوب</p>
						<br>
						<br>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
  
      
     
		{%endblock %}  